# Generated by Django 5.1.6 on 2025-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_playlist_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
    ]
